Update test-one.yml

diff --git a/.github/workflows/test-one.yml b/.github/workflows/test-one.yml
--- a/.github/workflows/test-one.yml
+++ b/.github/workflows/test-one.yml
@@ -5,26 +5,27 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: fail
-        run: sleep 3
+        run: exit 1
   final-job:
     runs-on: ubuntu-latest
     needs: [actual-job]
     steps:
-      - run: echo "final"
-  report-job:
+      - name: final
+        run: echo "final"
+  report-job-success:
     runs-on: ubuntu-latest
     needs: [final-job]
-    if: always()
+    if: success()
     steps:
       - name: slack
         run: |
-           STATUSES="${{join(needs.*.result,'')}}" # Combines all results in one long string
-           echo "statuses: $STATUSES"
-           FILTERED="${STATUSES//success/}" # Removes all success statuses
-           echo "filtered: $FILTERED"
-           STATUS=$([[ -z "$FILTERED" ]] && echo "success" || echo "failure") # if not empty, its a failure
-           echo "status: $STATUS"
-           echo "${{toJSON(needs)}}"
-#          echo "slack ${{job.status}}"
-#          echo "${{needs.actual-job.result == 'success' && 'succ' || 'fail'}}"
-#          echo "gas ${{github.action_status}}"
+           echo "success"
+  report-job-failure:
+    runs-on: ubuntu-latest
+    needs: [final-job]
+    if: failure()
+    steps:
+      - name: slack
+        run: |
+           echo "failure"
+           
